### ISSUE TITLE
Widget does not start verification when focusing input elements

### ISSUE THREAD

**Issue by danielband** [FriendlyCaptcha/friendly-captcha-sdk#18]
https://github.com/user-attachments/assets/90dbb108-bf2a-45e1-81f6-c8b60c6cbdc0

Used version: 0.1.9

Steps:
1. Download the sdk and add the files to your project
2. Add both scripts to the project
3. Add the widget
frcaptcha.createWidget({
        element: wrapper,
        sitekey: siteKey,
        startMode: 'focus',
        formFieldName: inputName
});

Expected result:
The widget should start validating on form focus

Result:
The widget is activating but does not start the verification process. This is in contrast to friendly challenge v1, where this works.

**Comment by elernonelma** [comment]
up!

**Comment by elernonelma** [comment]
It may not be related but I guess it is, following the documentation about the WidgetHandle.start() method https://developer.friendlycaptcha.com/docs/v2/sdk/reference/sdk.widgethandle.start ; I got the same result of @danielband with the focus start mode.

**Comment by danielband** [comment]
> It may not be related but I guess it is, following the documentation about the WidgetHandle.start() method https://developer.friendlycaptcha.com/docs/v2/sdk/reference/sdk.widgethandle.start ; I got the same result of @danielband with the focus start mode.

I think so, the noninteractive mode does not seem to work.

**Comment by gzuidhof** [comment]
Hi @elernonelma,

The challenge will be started in the background, and in most cases at the end of the form - by the time the user gets there - when they click the widget it will be instant. `start()` in this case triggers the background solving.

We now expose a `Widget Mode` setting in our dashboard that allows you to choose the old behavior, in which the user never has to press the widget. By having the single click, it allows us to detect automated browsers better - so there is some reduction in protection with the `noninteractive` mode setting (but of course you can always switch back later).

I hope this helps explain it, let me know if something doesn't make sense

**Comment by elernonelma** [comment]
Thank you @gzuidhof for the explanations, I'll take a look tomorrow at the impact of widget modes on my side.

NB: It's still not really clear what means interactive mode & noninteractive mode in the documentation.

I'm not sure it's the right place to discuss about that, but I guess it would increment the detection if we could pass a javascript MouseEvent/KeyBoardEvent into the WidgetHandle.start() method?

Thanks.

**Comment by greenberga** [comment]
Hi @elernonelma, we just published some [documentation on the **Widget Mode**](https://developer.friendlycaptcha.com/docs/v2/sdk/configuration#widget-mode). Perhaps that and the section on [the `data-start` attribute](https://developer.friendlycaptcha.com/docs/v2/sdk/configuration#data-start-attribute) can help to clarify. Thank you for your attention here.
